// src/imageList.ts
export const imageList = [
  { url: '/Photos/DSC00460.JPG', tags: ['paysage', 'nature'] },
  { url: '/Photos/DSC_1295.JPG', tags: ['portrait'] },
  { url: '/Photos/DSC_1303.JPG', tags: ['nature'] },
  { url: '/Photos/DSC_1305.JPG', tags: ['ville'] },
  { url: '/Photos/DSC_1308.JPG', tags: ['paysage'] },
  { url: '/Photos/DSC_1310.JPG', tags: ['portrait'] },
  { url: '/Photos/DSC_1320.JPG', tags: ['nature'] },
  { url: '/Photos/DSC_1322.JPG', tags: ['ville'] },
  { url: '/Photos/DSC_1324.JPG', tags: ['paysage'] },
  { url: '/Photos/DSC_1326.JPG', tags: ['portrait'] },
  { url: '/Photos/DSC_1339.JPG', tags: ['nature'] },
  { url: '/Photos/DSC_1342.JPG', tags: ['ville'] },
  { url: '/Photos/DSC_1359.JPG', tags: ['paysage'] },
  { url: '/Photos/DSC_1362.JPG', tags: ['portrait'] },
  { url: '/Photos/DSC_1364.JPG', tags: ['nature'] },
  { url: '/Photos/DSC_1368.JPG', tags: ['ville'] },
  { url: '/Photos/DSC_1383.JPG', tags: ['paysage'] },
  { url: '/Photos/DSC_1394.JPG', tags: ['portrait'] },
  { url: '/Photos/DSC_1410.JPG', tags: ['nature'] },
  { url: '/Photos/DSC_1441.JPG', tags: ['ville'] },
  { url: '/Photos/DSC_1481.JPG', tags: ['paysage'] },
  { url: '/Photos/DSC_1521.JPG', tags: ['portrait'] },
  { url: '/Photos/DSC_1533.JPG', tags: ['nature'] },
  { url: '/Photos/DSC_1536.JPG', tags: ['ville'] },
  { url: '/Photos/DSC_1541.JPG', tags: ['paysage'] },
  { url: '/Photos/DSC_1550.JPG', tags: ['portrait'] },
  { url: '/Photos/DSC_1560.JPG', tags: ['nature'] },
  { url: '/Photos/DSC_1570.JPG', tags: ['ville'] },
  { url: '/Photos/DSC_1576.JPG', tags: ['paysage'] },
  { url: '/Photos/DSC_1581.JPG', tags: ['portrait'] },
  { url: '/Photos/DSC_1594.JPG', tags: ['nature'] },
  { url: '/Photos/DSC_1598.JPG', tags: ['ville'] },
];